routes/web.php
<?php

use App\Http\Controllers\ArticlesController;
use App\Http\Controllers\AuthorsController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomepageController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomepageController::class, 'index'])->name('homepage');

Route::middleware(['auth'])->group(function() {

/***
 *  Articles Routes
 */
// Route::get('articles', [ArticlesController::class, 'index'])->name('articles.index');
// Route::get('articles/create', [ArticlesController::class, 'create'])->name('articles.create');
// Route::post('articles/store', [ArticlesController::class, 'store'])->name('articles.store');
// Route::get('/articles/show/{id}', [ArticlesController::class, 'show'])->(articles)

    Route::group([
        'prefix' => 'articles',
        'as' => 'articles.',
        'controller' => ArticlesController::class,
        // 'middleware' => ['auth']
    ], function() {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/show/{id}', 'show')->name('show');
        Route::get('/{id}/edit', 'edit')->name('edit');
        Route::patch('/{id}/update', 'update')->name('update');
        Route::delete('/{id}/delete', 'destroy')->name('delete');
    });

    /***
     *  Authors Routes
     */
    Route::get('authors', [AuthorsController::class, 'index'])->name('authors.index');

    /***
     *  Categories Routes
     */
    // Route::get('categories', [CategoryController::class, 'index'])->name('categories.index');

    Route::resource('categories', CategoryController::class)->except('show');

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

});
Auth::routes();

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    // Fields that are mass assignable 
    protected $fillable = [
        'name'
    ];

    public function articles()
    {
        return $this->hasMany(Article::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryFormRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index()
    {
        return view('categories.index', [
            'categories' => Category::all()
        ]);
    }

    public function create()
    {
        return view('categories.create');
    }

    public function store(CategoryFormRequest $request)
    {
        Category::create($request->all());

        return redirect()->route('categories.index');
    }

    public function show($id)
    {
        return view('categories.show', [
            'category' => Category::findOrFail($id)
        ]);
    }

    public function edit(Category $category)
    {
        /**
         * This is another implementation 
        */
        return view('categories.edit', [
            'category' => $category
        ]);
    }

    public function update(CategoryFormRequest $request, $id)
    {
        $category = Category::findOrFail($id);

        $category->update($request->all());

        return redirect()->route('categories.index', $category->id);
    }

    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->route('categories.index');
    }

}

resources/views/categories/create.blade.php
@extends('layouts.app')
@section('title', 'Create Categories')
@section('content')
<div class="card">
	<div class="card-body">
		<form action="{{ route('categories.store') }}" method="POST">
			@csrf
			<div class="mb-3">
			  <label for="name" class="form-label">Name</label>
			  <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name') }}" >
			  @error('name')
			      <span class="invalid-feedback" role="alert">
			          <strong>{{ $message }}</strong>
			      </span>
			  @enderror
			</div>
			<div class="mb-3">
				<button type="submit" class="btn btn-success">Submit</button>
			</div>
		</form>
	</div>
</div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit Category')
@section('content')
<div class="card">
	<div class="card-body">
		<form action="{{ route('categories.update', $category->id) }}" method="POST">
			@csrf
			@method('PATCH')
			<div class="mb-3">
			  <label for="name" class="form-label">Name</label>
			  <input type="text" class="form-control @error('name') is-invalid @enderror" id="names" name="name" value="{{ old('name') ?? $category->name }}" >
			  @error('name')
			      <span class="invalid-feedback" role="alert">
			          <strong>{{ $message }}</strong>
			      </span>
			  @enderror
			</div>
			<div class="mb-3">
				<button type="submit" class="btn btn-success">Update</button>
			</div>
		</form>
	</div>
</div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')
@section('title', 'Categories')
@section('content')
<div class="card">
	<div class="card-title">Categories</div>
	<a href="{{ route('categories.create') }}" class="btn btn-primary">Create</a>
	<div class="card-body">
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>ID</th>
					<th>Name</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach($categories as $key => $category)
				   <tr>
				   	<td>{{ ++$key }}</td>
				   	<td>{{ $category->name }}</td>
				   	<td>{{ $category->created_at->toDayDateTimeString() }}</td>
				   	<td>
				   		<a href="{{ route('categories.edit', $category->id) }}" class="btn btn-warning btn-sm">Edit</a>
				   		<form action="{{ route('categories.destroy', $category->id) }}" method="POST" onClick="return confirm('Are you sure?')">
                              @csrf
                              @method('DELETE')
                              <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
				   	</td>
				   </tr>
				@endforeach
			</tbody>
		</table>
	</div>
</div>
@endsection