routes/web.php
<?php

use App\Http\Controllers\ArticlesController;
use App\Http\Controllers\AuthorsController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomepageController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomepageController::class, 'index'])->name('homepage');

Route::middleware(['auth'])->group(function() {

/***
 *  Articles Routes
 */
// Route::get('articles', [ArticlesController::class, 'index'])->name('articles.index');
// Route::get('articles/create', [ArticlesController::class, 'create'])->name('articles.create');
// Route::post('articles/store', [ArticlesController::class, 'store'])->name('articles.store');
// Route::get('/articles/show/{id}', [ArticlesController::class, 'show'])->(articles)

    Route::group([
        'prefix' => 'articles',
        'as' => 'articles.',
        'controller' => ArticlesController::class,
        // 'middleware' => ['auth']
    ], function() {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/show/{id}', 'show')->name('show');
        Route::get('/{id}/edit', 'edit')->name('edit');
        Route::patch('/{id}/update', 'update')->name('update');
        Route::delete('/{id}/delete', 'destroy')->name('delete');
    });

    /***
     *  Authors Routes
     */
    Route::get('authors', [AuthorsController::class, 'index'])->name('authors.index');

    /***
     *  Categories Routes
     */
    // Route::get('categories', [CategoryController::class, 'index'])->name('categories.index');

    Route::resource('categories', CategoryController::class)->except('show');

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

});
Auth::routes();

app/Models/Article.php
<?php

namespace App\Models;

use App\Models\Category;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'excerpt',
        'content',
        'image',
        'category_id'
    ];

    // protected $guarded = []

    public function category()
    {
        return $this->belongsTo(Category::class);
    }


}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ArticleFormRequest;
use App\Mail\TestMail;
use App\Models\Article;
use App\Models\Category;
use App\Notifications\ArticleCreated;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use Mail;
class ArticlesController extends Controller
{
    public function __construct()
    {
        // $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Session::put('name', 'Mahmud Bakale');
        $articles = DB::table('articles')
        ->select('id', 'title', 'excerpt', 'created_at')->get();
        // $articles = Article::get(['id', 'title', 'excerpt', 'created_at']);
        return view('articles.index', [
            'articles' => $articles
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('articles.create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleFormRequest $request)
    {
        DB::transaction(function() use ($request) {
        // $article = new Article();
        // $article->title = $request->title;
        // $article->excerpt = $request->excerpt;
        // $article->content = $request->content;
        // $article->image = $request->image->store('images');
        // $article->save();


        // DB::table('articles')
        // ->insert([
        //     'title' => $request->title,
        //     'excerpt' => $request->excerpt,
        //     'content' => $request->content,
        //     'category_id' => $request->category_id,
        //     'image' => $request->image->storeAs('public/images', $request->image->getClientOriginalName())
        // ]);
        $article = Article::create([
            'title' => $request->title,
            'excerpt' => $request->excerpt,
            'content' => $request->content,
            'category_id' => $request->category_id
            'image' => $request->image->storeAs('public/images', $request->image->getClientOriginalName())
        ]);
        auth()->user()->notify(new ArticleCreated($article));

        // $article = Article::create($request->except('image'));

        // $article = Article::create($request->except('image'));


        // $article->image = $request->image->store('images');
        // $article->save();
        // Mail::to('bakale.mahmud@gmail.com')->send(new TestMail());
        });

            
            session()->flash('success', 'Article Created Successfully');
            return redirect()->route('articles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $article = DB::table('articles')
        // ->where('id', $id)->first();

        $article = Article::findOrFail($id);

        return view('articles.show', [
            'article' => $article
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $article = DB::table('articles')
        ->where('id', $id)->first();
        // $article = Article::findOrFail($id);

        return view('articles.edit', [
            'article' => $article,
            'categories' => Category::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleFormRequest $request, $id)
    {
        // $article = Article::find($id);
        // $article->title = $request->title;
        // $article->excerpt = $request->excerpt;
        // $article->content = $request->content;
        
        if($request->hasFile('image')) {
            $article->image = $request->image->store('images');
        }
        
        // $article->save();

        // $article->update([
        //     'title' => $request->title,
        //     'excerpt' => $request->excerpt,
        //     'content' => $request->content,
        //     // 'image' => $request->image->store('images')
        // ]);

        // $article = $article->update($request->except('image'));


        DB::table('articles')
        ->where('id', $id)
        ->update([ 
            'title' => $request->title,
            'excerpt' => $request->excerpt,
            'content' => $request->content,
            'category_id' => $request->category_id,
            // 'image' => $request->image->storeAs('public/images', $request->image->getClientOriginalName())
        ]);

        // $article->update($request->except('image'));


        // $article->image = $request
        //     ->image
        //     ->storeAs('public/images', $request->image->getClientOriginalName());
        
        // $article->save();

        return redirect()->route('articles.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // $article = Article::findOrFail($id);

        // $article->delete();

        DB::table('articles')
        ->where('id', $id)->delete();

        return redirect()->route('articles.index');
    }
}

resources/views/articles/create.blade.php
@extends('layouts.app')
@section('title', 'Create Article')
@section('content')
<div class="card">
	<div class="card-body">
		<form action="{{ route('articles.store') }}" method="POST" enctype="multipart/form-data">
			@csrf
			<div class="mb-3">
			  <label for="title" class="form-label">Title</label>
			  <input type="text" class="form-control @error('title') is-invalid @enderror" id="titles" name="title" value="{{ old('title') }}" >
			  @error('title')
			      <span class="invalid-feedback" role="alert">
			          <strong>{{ $message }}</strong>
			      </span>
			  @enderror
			</div>
			<div class="mb-3">
			  <label for="content" class="form-label">Category</label>
				<select name="category_id" id="" class="form-control">
					@foreach($categories as $category)
						<option value="{{$category->id}}">{{$category->name}}</option>
					@endforeach
				</select>
			  @error('content')
			      <span class="invalid-feedback" role="alert">
			          <strong>{{ $message }}</strong>
			      </span>
			  @enderror
			</div>
			<div class="mb-3">
			  <label for="excerpt" class="form-label">Excerpt</label>
			  <textarea class="form-control @error('excerpt') is-invalid @enderror" name="excerpt"  rows="3">{{old('excerpt')}}</textarea>
			  @error('excerpt')
			      <span class="invalid-feedback" role="alert">
			          <strong>{{ $message }}</strong>
			      </span>
			  @enderror
			</div>
			<div class="mb-3">
			  <label for="content" class="form-label">Content</label>
			  <textarea class="form-control @error('content') is-invalid @enderror"  id="content" name="content" rows="6">{{old('content')}}</textarea>
			  @error('content')
			      <span class="invalid-feedback" role="alert">
			          <strong>{{ $message }}</strong>
			      </span>
			  @enderror
			</div>
			<div class="mb-3">
				<input type="file" name="image" class="form-control @error('image') is-invalid @enderror">
				@error('image')
				    <span class="invalid-feedback" role="alert">
				        <strong>{{ $message }}</strong>
				    </span>
				@enderror
			</div>
			<div class="mb-3">
				<button type="submit" class="btn btn-success">Submit</button>
			</div>
		</form>
	</div>
</div>
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit Article')
@section('content')
<div class="card">
	<div class="card-body">
		<form action="{{ route('articles.update', $article->id) }}" method="POST" enctype="multipart/form-data">
			@csrf
			@method('PATCH')
			<div class="mb-3">
			  <label for="title" class="form-label">Title</label>
			  <input type="text" class="form-control @error('title') is-invalid @enderror" id="titles" name="title" value="{{ old('title') ?? $article->title }}" >
			  @error('title')
			      <span class="invalid-feedback" role="alert">
			          <strong>{{ $message }}</strong>
			      </span>
			  @enderror
			</div>
			<div class="mb-3">
			  <label for="content" class="form-label">Category</label>
				<select name="category_id" id="" class="form-control">
					@foreach($categories as $category)
						<option {{ ($article->category_id === $category->id) ? 'selected' : '' }} value="{{$category->id}}">{{$category->name}}</option>
					@endforeach
				</select>
			  @error('content')
			      <span class="invalid-feedback" role="alert">
			          <strong>{{ $message }}</strong>
			      </span>
			  @enderror
			</div>
			<div class="mb-3">
			  <label for="excerpt" class="form-label">Excerpt</label>
			  <textarea class="form-control @error('excerpt') is-invalid @enderror" name="excerpt"  rows="3">{{old('excerpt') ?? $article->excerpt}}</textarea>
			  @error('excerpt')
			      <span class="invalid-feedback" role="alert">
			          <strong>{{ $message }}</strong>
			      </span>
			  @enderror
			</div>
			<div class="mb-3">
			  <label for="content" class="form-label">Content</label>
			  <textarea class="form-control @error('content') is-invalid @enderror"  id="content" name="content" rows="6">{{old('content') ?? $article->content}}</textarea>
			  @error('content')
			      <span class="invalid-feedback" role="alert">
			          <strong>{{ $message }}</strong>
			      </span>
			  @enderror
			</div>
			<div class="mb-3">
				<input type="file" name="image" class="form-control @error('image') is-invalid @enderror">
				@error('image')
				    <span class="invalid-feedback" role="alert">
				        <strong>{{ $message }}</strong>
				    </span>
				@enderror
			</div>
			<div class="mb-3">
				<button type="submit" class="btn btn-success">Update</button>
			</div>
		</form>
	</div>
</div>
@endsection

resources/views/articles/index.blade.php
@extends('layouts.app')
@section('title', 'Articles')
@section('content')
<div class="card">
	<div class="card-title">Articles</div>
	<a href="{{ route('articles.create') }}" class="btn btn-primary">Create</a>
	<div class="card-body">
		@if(Session::has('success'))
			<div class="alert alert-success">{{Session::get('success')}}</div>
		@endif
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>ID</th>
					<th>Title</th>
					<th>Excerpt</th>
					<th>Created At</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach($articles as $key => $article)
				   <tr>
				   	<td>{{ ++$key }}</td>
				   	<td>{{ $article->title }}</td>
				   	<td>{{ $article->excerpt }}</td>
				   	<td>{{ $article->created_at }}</td>
				   	<td>
				   		<a href="{{ route('articles.show', $article->id) }}" class="btn btn-primary btn-sm">Show</a>
				   		<a href="{{ route('articles.edit', $article->id) }}" class="btn btn-warning btn-sm">Edit</a>
				   		<form action="{{ route('articles.delete', $article->id) }}" method="POST" onClick="return confirm('Are you sure?')">
                              @csrf
                              @method('DELETE')
                              <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
				   	</td>
				   </tr>
				@endforeach
			</tbody>
		</table>
	</div>
</div>
@endsection

resources/views/articles/show.blade.php
@extends('layouts.app')
@section('title', $article->title)
@section('content')
<div class="card">
	<div class="card-title">{{ $article->title }}</div>
	<div class="card-body">
		<table class="table table-bordered">
			<tbody>
					<tr>
					   	<th>Title</th>
   					   	<td>{{ $article->title }}</td>
					</tr>
					<tr>
					   	<th>Category</th>
   					   	<td>{{ optional($article->category)->name ?? 'Not Available' }}</td>
					</tr>
					<tr>
					   	<th>Excerpt</th>
   					   	<td>{{ $article->excerpt }}</td>
					</tr>
					<tr>
					   	<th>Content</th>
   					   	<td>{{ $article->content }}</td>
					</tr>
					<tr>
					   	<th>Created At</th>
					   	<td>{{ $article->created_at }}</td>
					</tr>
					<tr>
					   	<th>Updated At</th>
					   	<td>{{ $article->updated_at }}</td>
					</tr>
					<tr>
					   	<th>Image</th>
					   	<td>
					   		<img src="{{ Storage::url($article->image) }}" alt="image" class="img-fluid">
					   	</td>
					</tr>
				   </tr>
			</tbody>
		</table>
	</div>
</div>
@endsection